mem("Chems", list("Ash","Oil","Acetone","Diethylamine","Phenol","Ammonia","Saltpetre","Lye","Lye Alternate","Lemoline","Silver Sulfadiazine","Styptic Powder","Saline-Glucose Solution","Synthflesh","Tirimol","Bicaridine","Libital","Probital","Kelotane","Aiuri","Lenturi","Anti-Toxin","Charcoal","Thializid","Tricordrazine","Tribalordrazine","Regenerative Jelly","Cryoxadone","Pyroxadone","Clonexadone","Mannitol","Neurine","BurnMix","Cap Mix","Salicyclic Acid","Oxandrolone","Rhigoxane","Salbutamol","Omnizine","Honey","Earthsblood","Pentetic Acid","Perfluorodecalin","Atropine","Calomel","Mutadone","Bone Gel","Potassium Iodide","Seiver","Ephedrine","Formaldehyde","Diphenhydramine","Oculine","Inacusiate","Epinephrine","Antihol","Stimulants","Insulin","Strange Reagent","Life","Synaptizine","Rezadone","Spaceacillin","Miner's Salve","Haloperidol","Leporazine","Corazone","Psicodine","Energized Jelly","Grub Juice","Peptides","Silibinin","Polypyrylium Oligomers","Modafinil","Morphine","Liquid Solder","System Cleaner","Dexalin","Lavaland Extract","Musiver","Protozine","Sanguirite","Nicotine","Ketamine","Krokodil","Crank","Methamphetamine","Bath Salts","Aranesp","Happiness","Space Drugs","Mushroom Hallucinogen","Stabilizing Agent","Fluorosurfactant","Smoke","Smoke Powder","Flash Powder","Phlogiston","Napalm","Sonic Powder","Pyrosium","Cryostylane","Chlorine Trifluoride","Sorium","Liquid Dark Matter","Meth Explosion","Black Powder","Nitroglycerin","Explosion","Holy Explosion","EMP","Bee Explosion (Beesplosion)","Tesla Shock","Thermite","Barber's Aid","Bluespace Dust","Concentrated Barber's Aid","Candle","Carbon Dioxide","Carpet","Chicken Powder","Colorful Reagent","Condensed Capsaicin","Corgium","Cow Powder","Cryptobiolin","Drying Agent","Foaming Agent","Firefighting Foam","Fluorosulfuric Acid","Glycerol","Goat Powder","Gorilla Powder","Quantum Hair Dye","Laughter","Meat Product","Medicated Suture","Advanced Regenerative Mesh","Mourning Poultices","Mouse Powder","Metal Foam","Mitogen Metabolism Factor","Monkey Powder","Smart Foaming Agent","Peptide Conversion","Smart Metal Foam","Nitrous Oxide","Rad Scrub Plus","Gold Solidification","Plasma Solidification","Plastic Sheets","Royal Bee Jelly","Secret Sauce","Sheep Powder","Soap","Sodium Chloride","Space Cleaner","Spray Tan","Space Lube","Sterilizine","Synthmeat","Unstable Mutagen","Mushroom Paste Congealation","Virus Rations","Virus Food","Mutagenic Agar","Sucrose Agar","Weakened Virus Plasma","Virus Plasma","Decaying Uranium Gel","Unstable Uranium Gel","Stable Uranium Gel","Slime Mutation Toxin","Lizard Mutation Toxin","Stable Mutation Toxin","Advanced Mutation Toxin","Toxin","Bad Food","Coffee Grounds","Ground Tea Leaves","Chloral Hydrate","Mindbreaker Toxin","Impedrezene","Mute Toxin","Mime's Bane","Bone Hurting Juice","Mulligan Toxin","Lexorin","Initropidril","Tirizene","Tiring Solution","Polonium","Pancuronium","Sodium Thiopental","Sulfonal","Amanitin","Amatoxin","Lipolicide","Coniine","Curare","Histamine","Venom","Fentanyl","Cyanide","Carpotoxin","Zombie Powder","Ghoul Powder","Itching Powder","Mint Toxin","Slime Jelly","Frost Oil","Heparin","Teslium","Rotatium","Spewium","Anacea","Weed Killer","Pest Killer","Plant-B-Gone","Spore Toxin","Pax","Synthpax","Dizzying Solution","Fake Beer","Tranquility","Liquid Electricity","BZ Metabolites","Shadowfrost","Entropic Polypnium","Mushroom Powder","Tinea Luxor","Vitrium Froth"));
mem("Recipes", list("1 part Oil, Temperature 480K",
    "1 part Welding Fuel, 1 part Carbon, 1 part Hydrogen",
    "1 part Oil, 1 part Welding Fuel, 1 part Oxygen",
    "1 part Ammonia, 1 part Ethanol",
    "1 part Oil, 1 part Chlorine, 1 part Water",
    "3 parts Hydrogen, 1 part Nitrogen",
    "3 parts Oxygen, 1 part Potassium, 1 part Nitrogen",
    "1 part Sodium, 1 part Hydrogen, 1 part Oxygen",
    "1 part Ash, 1 part Water, 1 part Carbon",
    "Lemoline Cargo Crate, Or Strange Seeds",
    "1 part Ammonia, 1 part Silver, 1 part Sulfur, 1 part Oxygen, 1 part Chlorine",
    "1 part Aluminium, 1 part Hydrogen, 1 part Oxygen, 1 part Sulphuric Acid",
    "1 part Sodium Chloride, 1 part Water, 1 part Sugar",
    "1 part Styptic Powder, 1 part Blood, 1 part Carbon",
    "3 parts Nitrogen, 2 parts Acetone, 1 part Sulphuric Acid",
    "1 part Carbon, 1 part Oxygen, 1 part Sugar, 1 part Lemoline",
    "3 parts Phenol, 1 part Oxygen, 1 part Nitrogen",
    "1 part Copper, 2 parts Acetone, 1 part Phosphorus",
    "1 part Carbon, 1 part Silicon, 1 part Lemoline",
    "2 parts Ammonia, 1 part Sulphuric Acid, 2 parts Hydrogen",
    "1 part Ammonia, 1 part Silver, 1 part Sulfur, 1 part Oxygen, 1 part Bromine",
    "1 part Nitrogen, 1 part Silicon, 1 part Potassium, 1 part Lemoline",
    "1 part Sodium Chloride, 1 part Ash, Temperature 380K",
    "1 part Sulfur, 1 part Fluorine, 1 part Toxin, 1 part Nitrous Oxide",
    "1 part Kelotane, 1 part Bicaridine, 1 part Anti-Toxin",
    "5 parts Ash, 2 parts Vitrium Froth, 1 part Tinea Luxor, Temperature 420K",
    "1 part Tricordrazine, 1 part Slime Jelly",
    "1 part Acetone, 1 part Unstable Mutagen, 1 part Stable Plasma",
    "1 part Cryoxadone, 1 part Omnizine, 1 part Phlogiston, or 1 part Cryoxadone, 1 part Slime Jelly",
    "1 part Cryoxadone, 1 part Sodium, 5 units Plasma (catalyst)",
    "1 part Hydrogen, 1 part Water, 1 part Sugar",
    "1 part Acetone, 1 part Mannitol, 1 part Oxygen",
    "1 part Welding Fuel, 1 part Carbon, 1 part Iron, Temperature 700K",
    "10 parts Ash, 1 part Entropic Polypnium, Temperature 420K",
    "1 part Phenol, 1 part Sodium, 1 part Carbon, 1 part Oxygen, 1 part Sulphuric Acid",
    "3 parts Carbon, 1 part Phenol, 1 part Hydrogen, 1 part Oxygen",
    "3 parts Cryostylane, 1 part Bromine, 1 part Lye, Temperature 47K",
    "1 part Salicyclic Acid, 1 part Ammonia, 1 part Aluminium, 1 part Bromine, 1 part Lithium",
    "Grown from Ambrosia Deus or Lifeweed, Found in lollipops and warm donk-pockets",
    "Beekeeping",
    "Grown from Ambrosia Gaia",
    "1 part Cyanide, 1 part Formaldehyde, 1 part Ammonia, 1 part Welding Fuel, 1 part Sodium, 1 part Chlorine",
    "1 part Oil, 1 part Fluorine, 1 part Hydrogen, Temperature 370K",
    "1 part Acetone, 1 part Diethylamine, 1 part Phenol, 1 part Ethanol, 1 part Sulphuric Acid",
    "1 part Mercury, 1 part Chlorine, Temperature 374K",
    "1 part Acetone, 1 part Unstable Mutagen, 1 part Bromine",
    "10 parts Milk, 10 parts Carbon, Temperature 630K",
    "1 part Potassium, 1 part Iodine",
    "1 part Nitrogen, 1 part Potassium, 1 part Aluminium",
    "1 part Diethylamine, 1 part Oil, 1 part Hydrogen, 1 part Sugar",
    "1 part Ethanol, 1 part Oxygen, 1 part Silver, Temperature 420K",
    "1 part Diethylamine, 1 part Oil, 1 part Bromine, 1 part Carbon, 1 part Ethanol",
    "1 part Charcoal, 1 part Carbon, 1 part Hydrogen",
    "1 part Charcoal, 1 part Carbon, 1 part Water",
    "1 part Acetone, 1 part Diethylamine, 1 part Phenol, 1 part Chlorine, 1 part Hydrogen, 1 part Oxygen",
    "1 part Charcoal, 1 part Copper, 1 part Ethanol",
    "Traitor/Changeling Adrenals, Stimpack",
    "1 part Saline-Glucose Solution, 1 part Anti-Toxin, or NanoMed Plus",
    "1 part Unstable Mutagen, 1 part Rezadone, 1 part Holy Water",
    "1 part Strange Reagent, 1 part Synthflesh, 1 part Blood, Temperature 374K",
    "1 part Sugar, 1 part Lithium, 1 part Water",
    "1 part Carpotoxin, 1 part Cryptobiolin, 1 part Copper",
    "1 part Epinephrine, 1 part Cryptobiolin",
    "1 Part Oil, 1 part Iron, 1 Part Water",
    "1 part Oil, 1 part Potassium Iodide, 1 part Aluminium, 1 part Chlorine, 1 part Fluorine",
    "1 part Copper, 1 part Silicon, 5 units Plasma (catalyst)",
    "2 parts Phenol, 1 part Lithium",
    "2 parts Mannitol, 1 part Impedrezene, 2 parts Water",
    "1 part Teslium, 1 part Slime Jelly",
    "Grind Gold Grub Guts",
    "1 Nutriment, 1 Mitogen Metabolism Factor",
    "Grow Galaxy Thistle",
    "Grow Spaceman's Trumpet",
    "1 part Acetone, 1 part Diethylamine, 1 part Phenol, 1 part Ammonia, 1 part Sulphuric Acid, 1 unit Bromine (catalyst)",
    "2 parts Carbon, 2 parts Hydrogen, 1 part Ethanol, 1 part Oxygen, Temperature 480K",
    "1 part Ethanol, 1 part Copper, 1 part Silver, Temperature 370K",
    "1 part Ethanol, 1 part Chlorine, 2 parts Phenol, 1 part Potassium",
    "Suffocation",
    "Brute, burn",
    "Toxins",
    "Brute, Burn, Toxin, and Suffocation",
    "Bleeding and Organs",
    "Cigarettes",
    "3 parts Morphine, 3 parts Chloral Hydrate, 3 parts Fentanyl, 3 parts Epinephrine",
    "1 part Diphenhydramine, 1 part Morphine, 1 part Space Cleaner, 1 part Phosphorus, 1 part Potassium, 1 part Welding Fuel, Temperature 380K",
    "1 part Diphenhydramine, 1 part Ammonia, 1 part Lithium, 1 part Sulphuric Acid, 1 part Welding Fuel, Temperature 390K",
    "1 part Ephedrine, 1 part Hydrogen, 1 part Iodine, 1 part Phosphorus, 1 part Fluorosulfuric Acid, Temperature 374K",
    "1 part Saltpetre, 1 part Space Cleaner, 1 part Bad Food, 1 part Enzyme, 1 part Nutriment, 1 part Tea, 1 part Mercury, Temperature 374K",
    "1 part Epinephrine, 1 part Atropine, 1 part Morphine",
    "2 parts Nitrous Oxide, 1 part Epinephrine, 1 part Ethanol, 5 units Plasma (catalyst)",
    "1 part Lithium, 1 part Mercury, 1 part Sugar",
    "A strong hallucinogenic drug derived from certain species of mushroom. Causes jittering, dizziness, drugginess, twitching, and giggling",
    "1 part Iron, 1 part Oxygen, 1 part Hydrogen",
    "2 parts Carbon, 2 parts Fluorine, 1 part Sulphuric Acid",
    "1 part Phosphorus, 1 part Potassium, 1 part Sugar",
    "1 part Phosphorus, 1 part Potassium, 1 part Sugar, 1 part Stabilizing Agent (catalyst)",
    "1 part Aluminium, 1 part Potassium, 1 part Sulfur",
    "1 part Phosphorus, 1 part Sulphuric Acid, 1 part Stable Plasma",
    "1 part Oil, 1 part Welding Fuel, 1 part Ethanol",
    "1 part Oxygen, 1 part Cola, 1 part Phosphorus",
    "1 part Stable Plasma, 1 part Radium, 1 part Phosphorus",
    "1 part Water, 1 part Stable Plasma, 1 part Nitrogen",
    "3 parts Fluorine, 1 part Chlorine, Temperature 424K",
    "1 part Mercury, 1 part Oxygen, 1 part Nitrogen, 1 part Carbon",
    "1 part Stable Plasma, 1 part Radium, 1 part Carbon",
    "1 part Diethylamine, 1 part Iodine, 1 part Phosphorus, 1 part Hydrogen, Temperature 300K",
    "1 part Charcoal, 1 part Saltpetre, 1 part Sulfur",
    "1 part Glycerol, 1 part Fluorosulfuric Acid, 1 part Sulphuric Acid",
    "1 part Potassium, 1 part Water",
    "1 part Potassium, 1 part Holy Water",
    "1 part Iron, 1 part Uranium",
    "1 part Honey, 1 part Strange Reagent, 1 part Radium",
    "1 part Teslium, 1 part Water, or Heating Teslium to 474K",
    "1 part Aluminium, 1 part Iron, 1 part Oxygen",
    "1 part Carpet, 1 part Space Drugs, 1 part Radium",
    "Grind a bluespace crystal, Grind certain plants, Slimes",
    "1 part Barber's Aid, 1 part Unstable Mutagen",
    "5 parts Liquid Gibs, 5 parts Oxygen, Temperature 374K",
    "2 parts Oxygen, 1 part Carbon, Temperature 777K",
    "1 part Space Drugs, 1 part Blood",
    "1 part Egg Yolk, 1 part Liquid Gibs, 2 parts Nutriment, Temperature 500K",
    "1 part Triple Citrus, 1 part Cryoxadone, 1 part Space Drugs, 1 part Radium, 1 part Stable Plasma",
    "5 parts Ethanol, 1 part Capsaicin Oil",
    "1 part Colorful Reagent, 1 part Strange Reagent, 1 part Nutriment, 1 part Blood, Temperature 374K",
    "1 part Milk, 1 part Liquid Gibs, 2 parts Nutriment, Temperature 500K",
    "1 part Oxygen, 1 part Potassium, 1 part Sugar",
    "2 parts Stable Plasma, 1 part Ethanol, 1 part Sodium",
    "1 part Lithium, 1 part Hydrogen",
    "1 part Stabilizing Agent, 1 part Fluorosurfactant, 1 part Carbon, Temperature 200K",
    "1 part Fluorine, 1 part Hydrogen, 1 part Potassium, 1 part Sulphuric Acid, Temperature 380K",
    "3 parts Corn Oil, 1 part Sulphuric Acid",
    "1 part Plant-Be-Gone, 1 part Liquid Gibs, 2 parts Nutriment, Temperature 500K",
    "Grind a gorilla cube.",
    "1 part Colorful Reagent, 1 part Space Drugs, 1 part Radium",
    "1 part Sugar, 1 part Banana Juice",
    "10 parts Liquid Gibs, 10 parts Nutriment, 10 parts Carbon",
    "10 parts Cellulose, 20 parts Formaldehyde, 15 parts Polypyrylium Oligomers, or 10 parts Bicaridine, 20 parts Probital, 10 parts spaceacillin",
    "20 parts Cellulose, 20 parts Aloe Juice, 10 parts Sterilizine, or 10 parts Kelotane, 20 parts Lenturi, 10 parts Sterilizine",
    "10 parts Amanitin, 20 parts Cellulose, 20 parts Aloe Juice, or 15 parts Entropic Polypnium, 20 parts Cellulose, 12 parts Tinea Luxor",
    "1 part Blood, 1 part Liquid Gibs, 2 parts Nutriment, Temperature 500K",
    "3 parts Iron/Aluminium, 1 part Foaming Agent, 1 part Fluorosulfuric Acid",
    "Ingest Probital.",
    "Grind a monkey cube.",
    "3 parts Foaming Agent, 1 part Acetone, 1 part Iron",
    "1 part Nutriment, 1 part Mitogen Metabolism Factor",
    "3 parts Aluminium, 1 part Smart Foaming Agent, 1 part Fluorosulfuric Acid",
    "2 parts Ammonia, 2 parts Oxygen, 1 part Nitrogen, Temperature 525K",
    "1 part Potassium Iodide, 1 part Space Cleaner, 1 part Seiver, Temperature 200K",
    "20 parts Gold, 5 parts Frost Oil, 1 part Iron",
    "20 parts Plasma, 5 parts Iron, 5 parts Frost Oil",
    "5 parts Oil, 3 parts Ash, 2 parts Sulphuric Acid, Temperature 374K",
    "40 parts Honey, 10 parts Unstable Mutagen",
    "???",
    "1 part Carpet, 1 part Liquid Gibs, 2 parts Nutriment, Temperature 500K",
    "10 parts Lye, 10 parts Liquid Gibs, Temperature 374K",
    "1 part Sodium, 1 part Chlorine, 1 part Water",
    "1 part Ammonia, 1 part Water",
    "1 part Orange Juice, 1 part Oil or Corn Oil",
    "1 part Oxygen, 1 part Silicon, 1 part Water",
    "1 part Charcoal, 1 part Chlorine, 1 part Ethanol",
    "5 parts Blood, 1 part Cryoxadone",
    "1 part Chlorine, 1 part Phosphorus, 1 part Radium",
    "2 parts Gutlunch Honey, 2 parts Vitrium Froth, 2 parts Entropic Polypnium",
    "1 part Virus Food, 1 part Synaptizine",
    "5 parts Water, 5 parts Milk",
    "1 part Unstable Mutagen, 1 part Virus Food",
    "1 part Mutagenic Agar, 1 part Sugar, or 1 part Mutagenic Agar, 1 part Saline-Glucose Solution",
    "1 part Virus Plasma, 1 part Synaptizine",
    "1 part Virus Food, 1 part Plasma",
    "1 part Virus Food, 1 part Uranium",
    "1 part Virus Plasma, 5 parts Uranium",
    "1 part Plasma, 10 parts Uranium, 10 parts Silver or Gold",
    "Use Plasma on a green slime",
    "Use Radium on a green slime",
    "Use Blood on a green slime",
    "Use Plasma on a black slime",
    "Hacked Medbay Vendors, Emagged Chem Dispenser, Emagged Medibots",
    "From eating poorly made food",
    "Grinding coffee beans",
    "Grinding tea leaves",
    "3 parts Chlorine, 1 part Ethanol, 1 part Water",
    "1 part Charcoal, 1 part Hydrogen, 1 part Silicon",
    "1 part Mercury, 1 part Oxygen, 1 part Sugar",
    "2 parts Uranium, 1 part Water, 1 part Carbon",
    "1 part Mute Toxin, 1 part Nothing, 1 part Radium",
    "3 parts Itching Powder, 1 part Unstable Mutagen, 1 part Milk",
    "1 part Slime Mutation Toxin, 1 Part Unstable Mutagen, or Found in the Traitor Uplink",
    "1 part Plasma, 1 part Chloral Hydrate, 1 part Oxygen",
    "Poison Kit, Bioterror Spray",
    "Traitor Sleepypen, Emagged Soda Dispenser, Emagged Borg Hypo, Death Berries",
    "Peacekeeper Cyborgs",
    "Poison Kit, Bioterror Spray",
    "Poison Kit, Old Medibot",
    "Emagged Borg Hypo, Poison Kit, Bioterror Spray/Syringe/Dart, Emagged Medibot",
    "1 part Acetone, 1 part Diethylamine, 1 part Sulfur",
    "Destroying Angel",
    "Fly Amanita",
    "1 part Ephedrine, 1 part Diethylamine, 1 part Mercury",
    "Death Berries, Bioterror Spray/Syringe",
    "Poison Kit",
    "Omega Weed, Poison Kit, Formaldehyde, Venom, Itching Powder",
    "Poison Kit, Bioterror Spray, Giant Spider bites",
    "1 part Space Drugs, Temperature 674K",
    "1 part Oil, 1 part Ammonia, 1 part Oxygen, Temperature 380K",
    "Carp Filet, Koi Beans, Emagged Chem Dispenser",
    "5 parts Morphine, 5 parts Carpotoxin, 5 parts Copper",
    "1 part Epinephrine, 1 part Zombie Powder",
    "1 part Charcoal, 1 part Ammonia, 1 part Welding Fuel",
    "Mint, Emagged Chem Dispenser, Mushroom Shavings (Lavaland)",
    "Grinding an unused slime extract",
    "Blue Slimes or from grinding Ice Pepper",
    "1 part Formaldehyde, 1 part Sodium, 1 part Chlorine, 1 part Lithium",
    "1 Part Black Powder, 1 Part Silver, 1 Part Stable Plasma, Temperature 400K",
    "1 Part Teslium, 1 Part Mindbreaker Toxin, 1 Part Fentanyl",
    "Poison Kit",
    "1 Part Haloperidol, 1 Part Impedrezene, 1 Part Radium",
    "1 part Toxin, 4 parts Ammonia",
    "1 part Toxin, 4 parts Ethanol",
    "1 part Toxin, 4 parts Water",
    "Bioterror Spray, Blobs",
    "1 part Mindbreaker Toxin, 1 part Synaptizine, 1 part Water",
    "Peacekeeper Cyborgs, Slimes",
    "Peacekeeper Cyborgs",
    "Emagged Service Cyborgs",
    "Gondola Meat",
    "1 part Teslium, 2 parts Blood",
    "Breathing in BZ",
    "Shadowling",
    "Mushroom Cap (Inocybe), from tall mushrooms",
    "Grind mushroom caps or leaves",
    "Mushroom Stem (Embershroom)",
    "Cactus Fruit (Fruiting Cactus), Mushroom Leaf (Porcini)"));
mem("c"+"r"+"e"+"a"+"t"+"o"+"r", "Hel"+"lo! " + "I'm " + "B"+"o"+"b, " + "i " + "am " + "an " + "experienced " + "Station " + "Network " + "Admin, " + "i " + "have " + "been " + "on " + "several " + "stations " + "with " + "an " + "increasing " + "amount " + "of " + "tools " + "under " + "my " + "belt. " + "Rest " + "assured, " + "your " + "network " + "is " + "in " + "good " + "servers. "+"-"+"B"+"o"+"b "+"B"+"utt"+"er"+"fi"+"ll");
mem("JobList", list(
    "Assistant", "Greytider",
    "Tourist", "Stands in middle of danger",
    "Clerk", "Maintenance Fiend",
    "Janitor", "Slip Master",
    "Clown", "Funny Man",
    "Mime", "Mute",
    "Librarian", "Book Worm",
    "Botanist", "Green Fingers",
    "Chaplain", "Man of Faith",

    // Command
    "Captain",  "Keeper of Nukes",
    "Head of Personnel", "Head of Greytiders",
    "Head of Security", "Head of Security",
    "Chief Engineer", "Master Plasma Leaker",
    "Research Director", "Ai Wrangler",
    "Chief Medical Officer", "Dr. Faust",

    // Supply
    "Shaft Miner", "Shovel Knight",
    "Quartermaster", "The one who orders stuff",
    "Cargo Technician", "Pizza Boy",

    // Science
    "Scientist", "Nerd",
    "Roboticist", "Illegal Mech Builder",

    // Engineering
    "Signal Technician", "Signal God",
    "Atmospheric Technician", "Plasma Leaker",
    "Station Engineer", "Explosion Fixer",

    // Security
    "Security Officer", "Random Searcher",
    "Warden", "Prisoner Beater",
    "Lawyer", "Judge Dred",
    "Detective", "Smoking Gun",
    
    // Medical
    "Medical Doctor", "Wound Fixer",
    "Virologist", "Plague Doctor",
    "Mining Medic", "Raid Healer",
    "Genetics", "Abuses telekinesis",
    "Paramedic", "Suit Sensors!",
    "Psychiatrist", "Pill Giver",
    "Chemist", "Meth Maker",

    // AI-Borgs
    "PeaceKeeper Cyborg", "EGG",
    "Security Cyborg", "Alien Beater",
    "AI", "Silicon Overlord" ,
    "Engineering Cyborg", "The Fixer",
    "Janitor Cyborg", "The Cleaner",
    "Medical Cyborg", "The Doc",    
));
